apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swe
  name: swe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: swe_tomcat_1
        name: ksreddy4599/swe_tomcat_1:latest
        ports:
        - containerPort: 8080
